// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countAnswersByOption = `-- name: CountAnswersByOption :many
SELECT selected_option_id, count(*) AS answer_count
FROM answers
WHERE question_id = $1
GROUP BY selected_option_id
`

type CountAnswersByOptionRow struct {
	SelectedOptionID uuid.UUID `json:"selected_option_id"`
	AnswerCount      int64     `json:"answer_count"`
}

func (q *Queries) CountAnswersByOption(ctx context.Context, questionID uuid.UUID) ([]CountAnswersByOptionRow, error) {
	rows, err := q.db.Query(ctx, countAnswersByOption, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAnswersByOptionRow
	for rows.Next() {
		var i CountAnswersByOptionRow
		if err := rows.Scan(&i.SelectedOptionID, &i.AnswerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (game_id, question_id, player_id, selected_option_id, is_correct, points_awarded)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, game_id, question_id, player_id, selected_option_id, is_correct, points_awarded, answered_at
`

type CreateAnswerParams struct {
	GameID           uuid.UUID `json:"game_id"`
	QuestionID       uuid.UUID `json:"question_id"`
	PlayerID         uuid.UUID `json:"player_id"`
	SelectedOptionID uuid.UUID `json:"selected_option_id"`
	IsCorrect        bool      `json:"is_correct"`
	PointsAwarded    int32     `json:"points_awarded"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.GameID,
		arg.QuestionID,
		arg.PlayerID,
		arg.SelectedOptionID,
		arg.IsCorrect,
		arg.PointsAwarded,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.PlayerID,
		&i.SelectedOptionID,
		&i.IsCorrect,
		&i.PointsAwarded,
		&i.AnsweredAt,
	)
	return i, err
}

const getAnswer = `-- name: GetAnswer :one
SELECT id, game_id, question_id, player_id, selected_option_id, is_correct, points_awarded, answered_at FROM answers WHERE question_id = $1 AND player_id = $2
`

type GetAnswerParams struct {
	QuestionID uuid.UUID `json:"question_id"`
	PlayerID   uuid.UUID `json:"player_id"`
}

func (q *Queries) GetAnswer(ctx context.Context, arg GetAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswer, arg.QuestionID, arg.PlayerID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.PlayerID,
		&i.SelectedOptionID,
		&i.IsCorrect,
		&i.PointsAwarded,
		&i.AnsweredAt,
	)
	return i, err
}
