// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayers = `-- name: CountPlayers :one
SELECT count(*) FROM players WHERE game_id = $1
`

func (q *Queries) CountPlayers(ctx context.Context, gameID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayers, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (quiz_id, code, created_by)
VALUES ($1, $2, $3)
RETURNING id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at
`

type CreateGameParams struct {
	QuizID    uuid.UUID `json:"quiz_id"`
	Code      string    `json:"code"`
	CreatedBy string    `json:"created_by"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.QuizID, arg.Code, arg.CreatedBy)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Code,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endGame = `-- name: EndGame :one
UPDATE games
SET status = 'ended', ended_at = now()
WHERE id = $1 AND status != 'ended'
RETURNING id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at
`

func (q *Queries) EndGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, endGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Code,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const gameCodeExists = `-- name: GameCodeExists :one
SELECT EXISTS (SELECT 1 FROM games WHERE code = $1)
`

func (q *Queries) GameCodeExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, gameCodeExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getGame = `-- name: GetGame :one
SELECT id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Code,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getGameByCode = `-- name: GetGameByCode :one
SELECT id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at FROM games WHERE code = $1
`

func (q *Queries) GetGameByCode(ctx context.Context, code string) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByCode, code)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Code,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at FROM games
WHERE $1::text IS NULL OR status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGames(ctx context.Context, status pgtype.Text) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Code,
			&i.Status,
			&i.CurrentQuestionIndex,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesByQuiz = `-- name: ListGamesByQuiz :many
SELECT id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at FROM games WHERE quiz_id = $1
`

func (q *Queries) ListGamesByQuiz(ctx context.Context, quizID uuid.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Code,
			&i.Status,
			&i.CurrentQuestionIndex,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentQuestionIndex = `-- name: SetCurrentQuestionIndex :one
UPDATE games
SET current_question_index = $2
WHERE id = $1 AND status = 'in_progress'
RETURNING id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at
`

type SetCurrentQuestionIndexParams struct {
	ID                   uuid.UUID   `json:"id"`
	CurrentQuestionIndex pgtype.Int4 `json:"current_question_index"`
}

func (q *Queries) SetCurrentQuestionIndex(ctx context.Context, arg SetCurrentQuestionIndexParams) (Game, error) {
	row := q.db.QueryRow(ctx, setCurrentQuestionIndex, arg.ID, arg.CurrentQuestionIndex)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Code,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status = 'in_progress', current_question_index = 0, started_at = now()
WHERE id = $1 AND status = 'lobby'
RETURNING id, quiz_id, code, status, current_question_index, created_by, created_at, started_at, ended_at
`

func (q *Queries) StartGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Code,
		&i.Status,
		&i.CurrentQuestionIndex,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}
