// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID               uuid.UUID          `json:"id"`
	GameID           uuid.UUID          `json:"game_id"`
	QuestionID       uuid.UUID          `json:"question_id"`
	PlayerID         uuid.UUID          `json:"player_id"`
	SelectedOptionID uuid.UUID          `json:"selected_option_id"`
	IsCorrect        bool               `json:"is_correct"`
	PointsAwarded    int32              `json:"points_awarded"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

type Game struct {
	ID                   uuid.UUID          `json:"id"`
	QuizID               uuid.UUID          `json:"quiz_id"`
	Code                 string             `json:"code"`
	Status               string             `json:"status"`
	CurrentQuestionIndex pgtype.Int4        `json:"current_question_index"`
	CreatedBy            string             `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	EndedAt              pgtype.Timestamptz `json:"ended_at"`
}

type Player struct {
	ID       uuid.UUID          `json:"id"`
	GameID   uuid.UUID          `json:"game_id"`
	ClientID uuid.UUID          `json:"client_id"`
	Nickname string             `json:"nickname"`
	Score    int32              `json:"score"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Question struct {
	ID               uuid.UUID          `json:"id"`
	QuizID           uuid.UUID          `json:"quiz_id"`
	Type             string             `json:"type"`
	Prompt           string             `json:"prompt"`
	Position         int32              `json:"position"`
	TimeLimitSeconds int32              `json:"time_limit_seconds"`
	Points           int32              `json:"points"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type QuestionOption struct {
	ID         uuid.UUID `json:"id"`
	QuestionID uuid.UUID `json:"question_id"`
	Text       string    `json:"text"`
	IsCorrect  bool      `json:"is_correct"`
	Position   int32     `json:"position"`
}

type Quiz struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Timed       bool               `json:"timed"`
}
