// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPlayerScore = `-- name: AddPlayerScore :exec
UPDATE players SET score = score + $2 WHERE id = $1
`

type AddPlayerScoreParams struct {
	ID    uuid.UUID `json:"id"`
	Score int32     `json:"score"`
}

func (q *Queries) AddPlayerScore(ctx context.Context, arg AddPlayerScoreParams) error {
	_, err := q.db.Exec(ctx, addPlayerScore, arg.ID, arg.Score)
	return err
}

const deletePlayer = `-- name: DeletePlayer :execrows
DELETE FROM players WHERE game_id = $1 AND client_id = $2
`

type DeletePlayerParams struct {
	GameID   uuid.UUID `json:"game_id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) DeletePlayer(ctx context.Context, arg DeletePlayerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayer, arg.GameID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, game_id, client_id, nickname, score, joined_at, color FROM players WHERE game_id = $1 AND client_id = $2
`

type GetPlayerParams struct {
	GameID   uuid.UUID `json:"game_id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, arg.GameID, arg.ClientID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ClientID,
		&i.Nickname,
		&i.Score,
		&i.JoinedAt,
		&i.Color,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, game_id, client_id, nickname, score, joined_at, color FROM players WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ClientID,
		&i.Nickname,
		&i.Score,
		&i.JoinedAt,
		&i.Color,
	)
	return i, err
}

const leaderboardByGame = `-- name: LeaderboardByGame :many
SELECT id, client_id, nickname, score, color,
       RANK() OVER (ORDER BY score DESC) AS rank
FROM players
WHERE game_id = $1
ORDER BY score DESC, joined_at ASC
`

type LeaderboardByGameRow struct {
	ID       uuid.UUID `json:"id"`
	ClientID uuid.UUID `json:"client_id"`
	Nickname string    `json:"nickname"`
	Score    int32     `json:"score"`
	Color    string    `json:"color"`
	Rank     int64     `json:"rank"`
}

func (q *Queries) LeaderboardByGame(ctx context.Context, gameID uuid.UUID) ([]LeaderboardByGameRow, error) {
	rows, err := q.db.Query(ctx, leaderboardByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardByGameRow
	for rows.Next() {
		var i LeaderboardByGameRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Nickname,
			&i.Score,
			&i.Color,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersByGame = `-- name: ListPlayersByGame :many
SELECT id, game_id, client_id, nickname, score, joined_at, color FROM players WHERE game_id = $1 ORDER BY joined_at ASC
`

func (q *Queries) ListPlayersByGame(ctx context.Context, gameID uuid.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayersByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ClientID,
			&i.Nickname,
			&i.Score,
			&i.JoinedAt,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayer = `-- name: UpsertPlayer :one
INSERT INTO players (game_id, client_id, nickname, color)
VALUES ($1, $2, $3, $4)
ON CONFLICT (game_id, client_id) DO UPDATE SET nickname = EXCLUDED.nickname, color = EXCLUDED.color
RETURNING id, game_id, client_id, nickname, score, joined_at, color
`

type UpsertPlayerParams struct {
	GameID   uuid.UUID `json:"game_id"`
	ClientID uuid.UUID `json:"client_id"`
	Nickname string    `json:"nickname"`
	Color    string    `json:"color"`
}

func (q *Queries) UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, upsertPlayer,
		arg.GameID,
		arg.ClientID,
		arg.Nickname,
		arg.Color,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ClientID,
		&i.Nickname,
		&i.Score,
		&i.JoinedAt,
		&i.Color,
	)
	return i, err
}
