// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPlayerScore(ctx context.Context, arg AddPlayerScoreParams) error
	CountAnswersByOption(ctx context.Context, questionID uuid.UUID) ([]CountAnswersByOptionRow, error)
	CountPlayers(ctx context.Context, gameID uuid.UUID) (int64, error)
	CountQuizQuestions(ctx context.Context, quizID uuid.UUID) (int64, error)
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuestionOption(ctx context.Context, arg CreateQuestionOptionParams) (QuestionOption, error)
	CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error)
	DeleteOptionsByQuestion(ctx context.Context, questionID uuid.UUID) error
	DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) (int64, error)
	DeleteQuiz(ctx context.Context, id uuid.UUID) (int64, error)
	EndGame(ctx context.Context, id uuid.UUID) (Game, error)
	GameCodeExists(ctx context.Context, code string) (bool, error)
	GetAnswer(ctx context.Context, arg GetAnswerParams) (Answer, error)
	GetGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetGameByCode(ctx context.Context, code string) (Game, error)
	GetOption(ctx context.Context, id uuid.UUID) (QuestionOption, error)
	GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error)
	GetQuestion(ctx context.Context, arg GetQuestionParams) (Question, error)
	GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error)
	GetQuiz(ctx context.Context, id uuid.UUID) (Quiz, error)
	LeaderboardByGame(ctx context.Context, gameID uuid.UUID) ([]LeaderboardByGameRow, error)
	ListGames(ctx context.Context, status pgtype.Text) ([]Game, error)
	ListOptionsByQuestion(ctx context.Context, questionID uuid.UUID) ([]QuestionOption, error)
	ListOptionsByQuestionIDs(ctx context.Context, questionIds []uuid.UUID) ([]QuestionOption, error)
	ListPlayersByGame(ctx context.Context, gameID uuid.UUID) ([]Player, error)
	ListQuestionsByQuiz(ctx context.Context, quizID uuid.UUID) ([]Question, error)
	ListQuizzes(ctx context.Context) ([]Quiz, error)
	NextQuestionPosition(ctx context.Context, quizID uuid.UUID) (int32, error)
	SetCurrentQuestionIndex(ctx context.Context, arg SetCurrentQuestionIndexParams) (Game, error)
	SetQuestionPosition(ctx context.Context, arg SetQuestionPositionParams) error
	StartGame(ctx context.Context, id uuid.UUID) (Game, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error)
	UpsertPlayer(ctx context.Context, arg UpsertPlayerParams) (Player, error)
}

var _ Querier = (*Queries)(nil)
