// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearQuestionMedia = `-- name: ClearQuestionMedia :one
UPDATE questions
SET media_key = NULL, media_type = NULL, updated_at = now()
WHERE id = $1 AND quiz_id = $2
RETURNING id, quiz_id, type, prompt, position, time_limit_seconds, points, created_at, updated_at, media_key, media_type
`

type ClearQuestionMediaParams struct {
	ID     uuid.UUID `json:"id"`
	QuizID uuid.UUID `json:"quiz_id"`
}

func (q *Queries) ClearQuestionMedia(ctx context.Context, arg ClearQuestionMediaParams) (Question, error) {
	row := q.db.QueryRow(ctx, clearQuestionMedia, arg.ID, arg.QuizID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Prompt,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaKey,
		&i.MediaType,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (quiz_id, type, prompt, position, time_limit_seconds, points)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, quiz_id, type, prompt, position, time_limit_seconds, points, created_at, updated_at, media_key, media_type
`

type CreateQuestionParams struct {
	QuizID           uuid.UUID `json:"quiz_id"`
	Type             string    `json:"type"`
	Prompt           string    `json:"prompt"`
	Position         int32     `json:"position"`
	TimeLimitSeconds int32     `json:"time_limit_seconds"`
	Points           int32     `json:"points"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.QuizID,
		arg.Type,
		arg.Prompt,
		arg.Position,
		arg.TimeLimitSeconds,
		arg.Points,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Prompt,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaKey,
		&i.MediaType,
	)
	return i, err
}

const createQuestionOption = `-- name: CreateQuestionOption :one
INSERT INTO question_options (question_id, text, is_correct, position)
VALUES ($1, $2, $3, $4)
RETURNING id, question_id, text, is_correct, position
`

type CreateQuestionOptionParams struct {
	QuestionID uuid.UUID `json:"question_id"`
	Text       string    `json:"text"`
	IsCorrect  bool      `json:"is_correct"`
	Position   int32     `json:"position"`
}

func (q *Queries) CreateQuestionOption(ctx context.Context, arg CreateQuestionOptionParams) (QuestionOption, error) {
	row := q.db.QueryRow(ctx, createQuestionOption,
		arg.QuestionID,
		arg.Text,
		arg.IsCorrect,
		arg.Position,
	)
	var i QuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.Position,
	)
	return i, err
}

const deleteOptionsByQuestion = `-- name: DeleteOptionsByQuestion :exec
DELETE FROM question_options WHERE question_id = $1
`

func (q *Queries) DeleteOptionsByQuestion(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOptionsByQuestion, questionID)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :execrows
DELETE FROM questions WHERE id = $1 AND quiz_id = $2
`

type DeleteQuestionParams struct {
	ID     uuid.UUID `json:"id"`
	QuizID uuid.UUID `json:"quiz_id"`
}

func (q *Queries) DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuestion, arg.ID, arg.QuizID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOption = `-- name: GetOption :one
SELECT id, question_id, text, is_correct, position FROM question_options WHERE id = $1
`

func (q *Queries) GetOption(ctx context.Context, id uuid.UUID) (QuestionOption, error) {
	row := q.db.QueryRow(ctx, getOption, id)
	var i QuestionOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.Position,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, quiz_id, type, prompt, position, time_limit_seconds, points, created_at, updated_at, media_key, media_type FROM questions WHERE id = $1 AND quiz_id = $2
`

type GetQuestionParams struct {
	ID     uuid.UUID `json:"id"`
	QuizID uuid.UUID `json:"quiz_id"`
}

func (q *Queries) GetQuestion(ctx context.Context, arg GetQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, arg.ID, arg.QuizID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Prompt,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaKey,
		&i.MediaType,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, quiz_id, type, prompt, position, time_limit_seconds, points, created_at, updated_at, media_key, media_type FROM questions WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Prompt,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaKey,
		&i.MediaType,
	)
	return i, err
}

const listOptionsByQuestion = `-- name: ListOptionsByQuestion :many
SELECT id, question_id, text, is_correct, position FROM question_options WHERE question_id = $1 ORDER BY position ASC
`

func (q *Queries) ListOptionsByQuestion(ctx context.Context, questionID uuid.UUID) ([]QuestionOption, error) {
	rows, err := q.db.Query(ctx, listOptionsByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionOption
	for rows.Next() {
		var i QuestionOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByQuestionIDs = `-- name: ListOptionsByQuestionIDs :many
SELECT id, question_id, text, is_correct, position FROM question_options WHERE question_id = ANY($1::uuid[]) ORDER BY question_id, position ASC
`

func (q *Queries) ListOptionsByQuestionIDs(ctx context.Context, questionIds []uuid.UUID) ([]QuestionOption, error) {
	rows, err := q.db.Query(ctx, listOptionsByQuestionIDs, questionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionOption
	for rows.Next() {
		var i QuestionOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByQuiz = `-- name: ListQuestionsByQuiz :many
SELECT id, quiz_id, type, prompt, position, time_limit_seconds, points, created_at, updated_at, media_key, media_type FROM questions WHERE quiz_id = $1 ORDER BY position ASC
`

func (q *Queries) ListQuestionsByQuiz(ctx context.Context, quizID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Type,
			&i.Prompt,
			&i.Position,
			&i.TimeLimitSeconds,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MediaKey,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextQuestionPosition = `-- name: NextQuestionPosition :one
SELECT COALESCE(MAX(position) + 1, 0)::int FROM questions WHERE quiz_id = $1
`

func (q *Queries) NextQuestionPosition(ctx context.Context, quizID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextQuestionPosition, quizID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setQuestionMedia = `-- name: SetQuestionMedia :one
UPDATE questions
SET media_key = $3, media_type = $4, updated_at = now()
WHERE id = $1 AND quiz_id = $2
RETURNING id, quiz_id, type, prompt, position, time_limit_seconds, points, created_at, updated_at, media_key, media_type
`

type SetQuestionMediaParams struct {
	ID        uuid.UUID   `json:"id"`
	QuizID    uuid.UUID   `json:"quiz_id"`
	MediaKey  pgtype.Text `json:"media_key"`
	MediaType pgtype.Text `json:"media_type"`
}

func (q *Queries) SetQuestionMedia(ctx context.Context, arg SetQuestionMediaParams) (Question, error) {
	row := q.db.QueryRow(ctx, setQuestionMedia,
		arg.ID,
		arg.QuizID,
		arg.MediaKey,
		arg.MediaType,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Prompt,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaKey,
		&i.MediaType,
	)
	return i, err
}

const setQuestionPosition = `-- name: SetQuestionPosition :exec
UPDATE questions SET position = $3 WHERE id = $1 AND quiz_id = $2
`

type SetQuestionPositionParams struct {
	ID       uuid.UUID `json:"id"`
	QuizID   uuid.UUID `json:"quiz_id"`
	Position int32     `json:"position"`
}

func (q *Queries) SetQuestionPosition(ctx context.Context, arg SetQuestionPositionParams) error {
	_, err := q.db.Exec(ctx, setQuestionPosition, arg.ID, arg.QuizID, arg.Position)
	return err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET prompt             = COALESCE($1, prompt),
    time_limit_seconds = COALESCE($2, time_limit_seconds),
    points              = COALESCE($3, points),
    updated_at          = now()
WHERE id = $4 AND quiz_id = $5
RETURNING id, quiz_id, type, prompt, position, time_limit_seconds, points, created_at, updated_at, media_key, media_type
`

type UpdateQuestionParams struct {
	Prompt           pgtype.Text `json:"prompt"`
	TimeLimitSeconds pgtype.Int4 `json:"time_limit_seconds"`
	Points           pgtype.Int4 `json:"points"`
	ID               uuid.UUID   `json:"id"`
	QuizID           uuid.UUID   `json:"quiz_id"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.Prompt,
		arg.TimeLimitSeconds,
		arg.Points,
		arg.ID,
		arg.QuizID,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Prompt,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MediaKey,
		&i.MediaType,
	)
	return i, err
}
