// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countQuizQuestions = `-- name: CountQuizQuestions :one
SELECT count(*) FROM questions WHERE quiz_id = $1
`

func (q *Queries) CountQuizQuestions(ctx context.Context, quizID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQuizQuestions, quizID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (title, description, created_by, timed)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, created_by, created_at, updated_at, timed
`

type CreateQuizParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedBy   string `json:"created_by"`
	Timed       bool   `json:"timed"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
		arg.Timed,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timed,
	)
	return i, err
}

const deleteQuiz = `-- name: DeleteQuiz :execrows
DELETE FROM quizzes WHERE id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuiz, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, title, description, created_by, created_at, updated_at, timed FROM quizzes WHERE id = $1
`

func (q *Queries) GetQuiz(ctx context.Context, id uuid.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timed,
	)
	return i, err
}

const getQuizSummary = `-- name: GetQuizSummary :one
SELECT id, title, description, created_by, created_at, updated_at, timed, question_count FROM quiz_summaries WHERE id = $1
`

func (q *Queries) GetQuizSummary(ctx context.Context, id uuid.UUID) (QuizSummary, error) {
	row := q.db.QueryRow(ctx, getQuizSummary, id)
	var i QuizSummary
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timed,
		&i.QuestionCount,
	)
	return i, err
}

const listQuizSummaries = `-- name: ListQuizSummaries :many
SELECT id, title, description, created_by, created_at, updated_at, timed, question_count FROM quiz_summaries ORDER BY created_at DESC
`

func (q *Queries) ListQuizSummaries(ctx context.Context) ([]QuizSummary, error) {
	rows, err := q.db.Query(ctx, listQuizSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizSummary
	for rows.Next() {
		var i QuizSummary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Timed,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes
SET title       = COALESCE($1, title),
    description = COALESCE($2, description),
    timed       = COALESCE($3, timed),
    updated_at  = now()
WHERE id = $4
RETURNING id, title, description, created_by, created_at, updated_at, timed
`

type UpdateQuizParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Timed       pgtype.Bool `json:"timed"`
	ID          uuid.UUID   `json:"id"`
}

// Not folded into a single-round-trip CTE like the games.sql mutations
// below: sqlc's analyzer (v1.31.1) can't resolve sqlc.narg()'d columns
// once the statement also joins in another relation for the question
// count, even fully qualified. Stays two round trips (this, then
// GetQuizSummary) rather than fight the tool further.
func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz,
		arg.Title,
		arg.Description,
		arg.Timed,
		arg.ID,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timed,
	)
	return i, err
}
