// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countQuizQuestions = `-- name: CountQuizQuestions :one
SELECT count(*) FROM questions WHERE quiz_id = $1
`

func (q *Queries) CountQuizQuestions(ctx context.Context, quizID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQuizQuestions, quizID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (title, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, title, description, created_by, created_at, updated_at
`

type CreateQuizParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz, arg.Title, arg.Description, arg.CreatedBy)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuiz = `-- name: DeleteQuiz :execrows
DELETE FROM quizzes WHERE id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuiz, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, title, description, created_by, created_at, updated_at FROM quizzes WHERE id = $1
`

func (q *Queries) GetQuiz(ctx context.Context, id uuid.UUID) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuizzes = `-- name: ListQuizzes :many
SELECT id, title, description, created_by, created_at, updated_at FROM quizzes ORDER BY created_at DESC
`

func (q *Queries) ListQuizzes(ctx context.Context) ([]Quiz, error) {
	rows, err := q.db.Query(ctx, listQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes
SET title       = COALESCE($1, title),
    description = COALESCE($2, description),
    updated_at  = now()
WHERE id = $3
RETURNING id, title, description, created_by, created_at, updated_at
`

type UpdateQuizParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRow(ctx, updateQuiz, arg.Title, arg.Description, arg.ID)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
