/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quizzes */
        get: operations["listQuizzes"];
        put?: never;
        /** Create a quiz */
        post: operations["createQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quizzes/{quizId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        /** Get a quiz with its questions */
        get: operations["getQuiz"];
        put?: never;
        post?: never;
        /** Delete a quiz and its questions. Rejected with 409 if any game has ever been created from it (lobby, in-progress, or ended) — a game is a historical record of a play session and shouldn't silently lose the quiz it was played from. */
        delete: operations["deleteQuiz"];
        options?: never;
        head?: never;
        /** Update a quiz */
        patch: operations["updateQuiz"];
        trace?: never;
    };
    "/admin/quizzes/{quizId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        /** List a quiz's questions, in order */
        get: operations["listQuestions"];
        put?: never;
        /** Add a question to a quiz */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quizzes/{quizId}/questions/order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Reorder a quiz's questions */
        put: operations["reorderQuestions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quizzes/{quizId}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        /** Get a question */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        /** Delete a question */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        /** Update a question */
        patch: operations["updateQuestion"];
        trace?: never;
    };
    "/admin/quizzes/{quizId}/questions/{questionId}/media": {
        parameters: {
            query?: never;
            header: {
                /** @description "Bearer <token>". Declared as a plain header parameter (checked manually in the handler) rather than a bearerAuth security scheme, and excluded from the usual OpenAPI request validation — both specifically for the media upload/delete operations, whose multipart request body must reach the handler unconsumed. The standard validator reads the whole multipart body to validate it, which would leave nothing for the handler to stream to storage. */
                Authorization: components["parameters"]["Authorization"];
            };
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach an optional image or audio fragment to a question, replacing any existing media. Shown to players when the question starts, and to the admin during the live game (to play audio centrally or reference the image while giving a hint). Requires an admin bearer token (see the Authorization parameter) — not secured via the usual bearerAuth scheme, since standard request validation would consume the multipart body before the handler can stream it to storage. */
        post: operations["uploadQuestionMedia"];
        /** Remove a question's attached media, if any. Uses the same manual Authorization check as the upload operation, for consistency between the two. */
        delete: operations["deleteQuestionMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game sessions */
        get: operations["listGames"];
        put?: never;
        /** Create a game session from a quiz */
        post: operations["createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        /** Get full game detail (admin view, includes correct answers) */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a game (lobby -> in_progress) */
        post: operations["startGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/next-question": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current question and advance to the next one, or end the game if exhausted */
        post: operations["advanceGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/review-question": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-show an already-asked question to players for reference (e.g. the admin advanced too fast, or wants to recap for latecomers). This is a pure broadcast — it never reopens the question for answers and never changes the game's actual current question, so "next question" always continues from wherever live play really is. Only questions at or before the current one can be reviewed. */
        post: operations["reviewQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/reset-answers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wipe every player's answer to one already-asked question and reverse any points it awarded, so it can be answered again. For recovering from a mistake (e.g. the wrong option was marked correct, or the question started before everyone was ready) — not for routine use. Only questions at or before the current one can be reset. */
        post: operations["resetQuestionAnswers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force-end a game */
        post: operations["endGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        /** Leaderboard snapshot for the admin dashboard */
        get: operations["getAdminLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/questions/{questionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
                questionId: string;
            };
            cookie?: never;
        };
        /** List every free-text answer submitted so far for one question in this game, for the admin to grade. Always empty for multiple_choice questions, which are scored automatically. */
        get: operations["listFreeTextAnswers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/answers/{answerId}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
                answerId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually grade one free-text answer: full points for the question if correct, none otherwise. Can be called again to change a grading mistake — the player's score is adjusted by the difference, not just added to. */
        post: operations["gradeAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/players/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
                clientId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a player from the lobby. Only allowed before the game starts — once it's in progress, removing someone mid-round would orphan their in-flight answers and skew scoring, so this is lobby-only. A kicked player can rejoin with a fresh nickname like anyone else; this isn't a ban. */
        delete: operations["kickPlayer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a game by its join code. Only allowed while the game is in the lobby — once it's in progress or has ended, this returns 409. */
        post: operations["joinGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public lookup of a game by join code */
        get: operations["getPublicGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{code}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public leaderboard snapshot */
        get: operations["getPublicLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        /** @enum {string} */
        QuestionType: "multiple_choice" | "free_text";
        /** @enum {string} */
        GameStatus: "lobby" | "in_progress" | "ended";
        Quiz: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            questionCount: number;
            /** @description Whether questions in this quiz show a countdown to players. When false, the admin paces the game manually with no time pressure shown. */
            timed: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        QuizDetail: components["schemas"]["Quiz"] & {
            questions: components["schemas"]["Question"][];
        };
        CreateQuizRequest: {
            title: string;
            description?: string;
            /** @default true */
            timed: boolean;
        };
        UpdateQuizRequest: {
            title?: string;
            description?: string;
            timed?: boolean;
        };
        QuestionOption: {
            /** Format: uuid */
            id: string;
            text: string;
        };
        QuestionOptionWithAnswer: components["schemas"]["QuestionOption"] & {
            isCorrect: boolean;
        };
        /** @enum {string} */
        MediaType: "image" | "audio";
        Question: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quizId: string;
            type: components["schemas"]["QuestionType"];
            prompt: string;
            position: number;
            timeLimitSeconds: number;
            points: number;
            options: components["schemas"]["QuestionOptionWithAnswer"][];
            /** @description Absent when the question has no attached media. */
            mediaUrl?: string;
            mediaType?: components["schemas"]["MediaType"];
        };
        CreateQuestionOption: {
            text: string;
            isCorrect: boolean;
        };
        /** @description options is required (2 or more) for multiple_choice and must be omitted (or empty) for free_text — free_text answers are always graded manually by the admin, not against a stored correct answer. */
        CreateQuestionRequest: {
            type: components["schemas"]["QuestionType"];
            prompt: string;
            /** @default 30 */
            timeLimitSeconds: number;
            /** @default 1000 */
            points: number;
            options?: components["schemas"]["CreateQuestionOption"][];
        };
        UpdateQuestionRequest: {
            prompt?: string;
            timeLimitSeconds?: number;
            points?: number;
            options?: components["schemas"]["CreateQuestionOption"][];
        };
        ReorderQuestionsRequest: {
            questionIds: string[];
        };
        ReviewQuestionRequest: {
            /** @description Must be at or before the game's current question index. */
            questionIndex: number;
        };
        ResetAnswersRequest: {
            /** @description Must be at or before the game's current question index. */
            questionIndex: number;
        };
        FreeTextAnswer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clientId: string;
            nickname: string;
            text: string;
            graded: boolean;
            /** @description Only meaningful once graded is true. */
            correct?: boolean;
            pointsAwarded?: number;
        };
        GradeAnswerRequest: {
            correct: boolean;
        };
        CreateGameRequest: {
            /** Format: uuid */
            quizId: string;
        };
        AdminGame: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quizId: string;
            quizTitle: string;
            code: string;
            status: components["schemas"]["GameStatus"];
            currentQuestionIndex: number | null;
            totalQuestions: number;
            playerCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description A small, curated set of cosmos-themed color choices — not a full color picker — so every player's pick reads clearly against the dark theme and stays distinct from the app's own semantic colors.
         * @enum {string}
         */
        PlayerColor: "nebula" | "comet" | "nova" | "quasar" | "solar" | "crimson";
        AdminPlayer: {
            /** Format: uuid */
            clientId: string;
            nickname: string;
            score: number;
            connected: boolean;
            color: components["schemas"]["PlayerColor"];
        };
        AdminGameDetail: components["schemas"]["AdminGame"] & {
            players: components["schemas"]["AdminPlayer"][];
        };
        JoinGameRequest: {
            code: string;
            nickname: string;
            /** @description One of PlayerColor's values, ideally — but deliberately typed as a plain string here (not $ref'd) rather than validated against the enum, so an unrecognized or omitted value falls back to a default instead of failing the whole join. */
            color?: string;
        };
        JoinGameResponse: {
            /** Format: uuid */
            gameId: string;
            code: string;
            status: components["schemas"]["GameStatus"];
            nickname: string;
            color: components["schemas"]["PlayerColor"];
        };
        PublicGame: {
            code: string;
            quizTitle: string;
            status: components["schemas"]["GameStatus"];
            playerCount: number;
        };
        LeaderboardEntry: {
            /** Format: uuid */
            clientId: string;
            nickname: string;
            score: number;
            rank: number;
            color: components["schemas"]["PlayerColor"];
        };
        Leaderboard: {
            entries: components["schemas"]["LeaderboardEntry"][];
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Valid token but missing the required role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with current resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        QuizId: string;
        QuestionId: string;
        GameId: string;
        ClientId: string;
        OptionalClientId: string;
        /** @description "Bearer <token>". Declared as a plain header parameter (checked manually in the handler) rather than a bearerAuth security scheme, and excluded from the usual OpenAPI request validation — both specifically for the media upload/delete operations, whose multipart request body must reach the handler unconsumed. The standard validator reads the whole multipart body to validate it, which would leave nothing for the handler to stream to storage. */
        Authorization: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listQuizzes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quizzes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizRequest"];
            };
        };
        responses: {
            /** @description Quiz created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quiz */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuizRequest"];
            };
        };
        responses: {
            /** @description Updated quiz */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionRequest"];
            };
        };
        responses: {
            /** @description Question created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reorderQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderQuestionsRequest"];
            };
        };
        responses: {
            /** @description Questions in new order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description Updated question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadQuestionMedia: {
        parameters: {
            query?: never;
            header: {
                /** @description "Bearer <token>". Declared as a plain header parameter (checked manually in the handler) rather than a bearerAuth security scheme, and excluded from the usual OpenAPI request validation — both specifically for the media upload/delete operations, whose multipart request body must reach the handler unconsumed. The standard validator reads the whole multipart body to validate it, which would leave nothing for the handler to stream to storage. */
                Authorization: components["parameters"]["Authorization"];
            };
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Media attached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteQuestionMedia: {
        parameters: {
            query?: never;
            header: {
                /** @description "Bearer <token>". Declared as a plain header parameter (checked manually in the handler) rather than a bearerAuth security scheme, and excluded from the usual OpenAPI request validation — both specifically for the media upload/delete operations, whose multipart request body must reach the handler unconsumed. The standard validator reads the whole multipart body to validate it, which would leave nothing for the handler to stream to storage. */
                Authorization: components["parameters"]["Authorization"];
            };
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGames: {
        parameters: {
            query?: {
                status?: components["schemas"]["GameStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameRequest"];
            };
        };
        responses: {
            /** @description Game created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGameDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    advanceGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game advanced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    reviewQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewQuestionRequest"];
            };
        };
        responses: {
            /** @description Question re-broadcast to players */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resetQuestionAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetAnswersRequest"];
            };
        };
        responses: {
            /** @description Answers reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    endGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAdminLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listFreeTextAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Free-text answers, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeTextAnswer"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    gradeAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
                answerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeAnswerRequest"];
            };
        };
        responses: {
            /** @description Answer graded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeTextAnswer"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    kickPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    joinGame: {
        parameters: {
            query?: never;
            header: {
                "X-Client-Id": components["parameters"]["ClientId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameRequest"];
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinGameResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getPublicGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicGame"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPublicLeaderboard: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Id"?: components["parameters"]["OptionalClientId"];
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
