/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quizzes */
        get: operations["listQuizzes"];
        put?: never;
        /** Create a quiz */
        post: operations["createQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quizzes/{quizId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        /** Get a quiz with its questions */
        get: operations["getQuiz"];
        put?: never;
        post?: never;
        /** Delete a quiz */
        delete: operations["deleteQuiz"];
        options?: never;
        head?: never;
        /** Update a quiz */
        patch: operations["updateQuiz"];
        trace?: never;
    };
    "/admin/quizzes/{quizId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        /** List a quiz's questions, in order */
        get: operations["listQuestions"];
        put?: never;
        /** Add a question to a quiz */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quizzes/{quizId}/questions/order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Reorder a quiz's questions */
        put: operations["reorderQuestions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/quizzes/{quizId}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        /** Get a question */
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        /** Delete a question */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        /** Update a question */
        patch: operations["updateQuestion"];
        trace?: never;
    };
    "/admin/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game sessions */
        get: operations["listGames"];
        put?: never;
        /** Create a game session from a quiz */
        post: operations["createGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        /** Get full game detail (admin view, includes correct answers) */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a game (lobby -> in_progress) */
        post: operations["startGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/next-question": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current question and advance to the next one, or end the game if exhausted */
        post: operations["advanceGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force-end a game */
        post: operations["endGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/games/{gameId}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        /** Leaderboard snapshot for the admin dashboard */
        get: operations["getAdminLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a game by its join code */
        post: operations["joinGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public lookup of a game by join code */
        get: operations["getPublicGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{code}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public leaderboard snapshot */
        get: operations["getPublicLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        /** @enum {string} */
        QuestionType: "multiple_choice";
        /** @enum {string} */
        GameStatus: "lobby" | "in_progress" | "ended";
        Quiz: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            questionCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        QuizDetail: components["schemas"]["Quiz"] & {
            questions: components["schemas"]["Question"][];
        };
        CreateQuizRequest: {
            title: string;
            description?: string;
        };
        UpdateQuizRequest: {
            title?: string;
            description?: string;
        };
        QuestionOption: {
            /** Format: uuid */
            id: string;
            text: string;
        };
        QuestionOptionWithAnswer: components["schemas"]["QuestionOption"] & {
            isCorrect: boolean;
        };
        Question: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quizId: string;
            type: components["schemas"]["QuestionType"];
            prompt: string;
            position: number;
            timeLimitSeconds: number;
            points: number;
            options: components["schemas"]["QuestionOptionWithAnswer"][];
        };
        CreateQuestionOption: {
            text: string;
            isCorrect: boolean;
        };
        CreateQuestionRequest: {
            type: components["schemas"]["QuestionType"];
            prompt: string;
            /** @default 30 */
            timeLimitSeconds: number;
            /** @default 1000 */
            points: number;
            options: components["schemas"]["CreateQuestionOption"][];
        };
        UpdateQuestionRequest: {
            prompt?: string;
            timeLimitSeconds?: number;
            points?: number;
            options?: components["schemas"]["CreateQuestionOption"][];
        };
        ReorderQuestionsRequest: {
            questionIds: string[];
        };
        CreateGameRequest: {
            /** Format: uuid */
            quizId: string;
        };
        AdminGame: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quizId: string;
            quizTitle: string;
            code: string;
            status: components["schemas"]["GameStatus"];
            currentQuestionIndex: number | null;
            totalQuestions: number;
            playerCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        AdminPlayer: {
            /** Format: uuid */
            clientId: string;
            nickname: string;
            score: number;
            connected: boolean;
        };
        AdminGameDetail: components["schemas"]["AdminGame"] & {
            players: components["schemas"]["AdminPlayer"][];
        };
        JoinGameRequest: {
            code: string;
            nickname: string;
        };
        JoinGameResponse: {
            /** Format: uuid */
            gameId: string;
            code: string;
            status: components["schemas"]["GameStatus"];
            nickname: string;
        };
        PublicGame: {
            code: string;
            quizTitle: string;
            status: components["schemas"]["GameStatus"];
            playerCount: number;
        };
        LeaderboardEntry: {
            /** Format: uuid */
            clientId: string;
            nickname: string;
            score: number;
            rank: number;
        };
        Leaderboard: {
            entries: components["schemas"]["LeaderboardEntry"][];
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Valid token but missing the required role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with current resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        QuizId: string;
        QuestionId: string;
        GameId: string;
        ClientId: string;
        OptionalClientId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listQuizzes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quizzes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizRequest"];
            };
        };
        responses: {
            /** @description Quiz created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quiz */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuizRequest"];
            };
        };
        responses: {
            /** @description Updated quiz */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionRequest"];
            };
        };
        responses: {
            /** @description Question created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reorderQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderQuestionsRequest"];
            };
        };
        responses: {
            /** @description Questions in new order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: components["parameters"]["QuizId"];
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description Updated question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGames: {
        parameters: {
            query?: {
                status?: components["schemas"]["GameStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameRequest"];
            };
        };
        responses: {
            /** @description Game created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGameDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    advanceGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game advanced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    endGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game ended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGame"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAdminLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    joinGame: {
        parameters: {
            query?: never;
            header: {
                "X-Client-Id": components["parameters"]["ClientId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameRequest"];
            };
        };
        responses: {
            /** @description Joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinGameResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getPublicGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Game summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicGame"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPublicLeaderboard: {
        parameters: {
            query?: never;
            header?: {
                "X-Client-Id"?: components["parameters"]["OptionalClientId"];
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
